### ISSUE TITLE
Massive amount of rerendering introduced in v2.9.0

### ISSUE THREAD

**Issue by johnnynomad** [TanStack/virtual#237]
Since v2.9.0 the component containing the `useVirtual` hook gets rerendered massively, like tens of times for every pixel scrolled. Subjectively this got even worse in v2.10.0

This codesandbox logs the rerenders to the console:
https://codesandbox.io/s/jovial-tesla-ii60w?file=/package.json
It has v2.8.2 preconfigured, as you can see the amount of rerendering is not great even in this version, but still within reasonable bounds.
Once you upgrade to v2.9.0 or v2.10.0 in the package.json the console will show you what I'm talking about.

**Comment by piecyk** [comment]
Yes, main change was to re-render on scroll event, overall the 2.10 should be breaking change #233

**Comment by bernhardc** [comment]
I don't quite understand. So is the rerendering a bug, or is it actually desired behavior that should have been a breaking change?

Just to clarify: the way I see it the `useVirtual` hook should only trigger a rerender when one of its return values changes.
This would the case only if the list of items to render (`virtualItems`) changes, or if the size of one of the currently rendered items changes.

**Comment by piecyk** [comment]
>  So is the rerendering a bug, or is it actually desired behavior that should have been a breaking change?

Yes, there is no bug, state is change only for scroll event, or in dynamic mode when size of item is different from cached one. It was changed here https://github.com/tannerlinsley/react-virtual/commit/cf19d1fb1a0c340733998700077e399fbfda2ee3

Did notice performance issues?

> Just to clarify: the way I see it the useVirtual hook should only trigger a rerender when one of its return values changes.

Maybe, soonish we will migrate to ts, and would do more performance testing.

**Comment by karex** [comment]
I think I bumped into this – or a related – issue as well. My case rather specialized (a table with variable row height and a non-defined width), but I thought it might worth to share here, it might shed some light on what's to be tracked down. I prepared a stripped down example [in this sandbox](https://codesandbox.io/s/depth-exceeded-demo-lp7v0?file=/src/index.js).

To trigger the error, simply scroll for a while (a couple of seconds will suffice). The app will fail with a "Maximum update depth exceeded" error, and the failing function from react-virtual is
`measureRef  in node_modules/react-virtual/dist/react-virtual.mjs:407:15`

For this to work (fail), at least two special conditions are needed: a table with an `auto` width (which leads to the table's width being adjusted for the differing content widths while scrolling), and that the rows of the table are of variable height (hence the width restriction on the table cells to achieve this with the Star Wars names). I know that these are atypical properties, but still it is a fact that it fails with versions greater than 2.8.2 and there's no error below 2.9.0, so there must be something here to look at.

(Actually I used [this codesandbox from you piecyk](https://codesandbox.io/s/poc-react-virtual-table-jyz0m?file=/src/index.js) as the base to finetune a flexible virtualized table, it was really useful, and wanted to say thanks for it!)

**Comment by bernhardc** [comment]
@karex Yes I think that's the same issue, I could reproduce this with your sandbox, especially when I'm scrolling slowly (which triggers lots of onScroll events).

@piecyk

> Did notice performance issues?

Since the virtualization itself improves the performance so much I think the rerendering issue isn't immediately visible, but I did a profiling comparison:

v2.8.2:
<img width="1032" alt="Screen Shot 2022-01-05 at 13 45 03" src="https://user-images.githubusercontent.com/15912049/148220875-bf39110c-f2a2-4843-8663-a4864d9cf3cc.png">

v2.10.0:
<img width="1129" alt="Screen Shot 2022-01-05 at 13 46 47" src="https://user-images.githubusercontent.com/15912049/148220892-73ce8523-4e1d-488f-ac7f-0fa401f6682f.png">

As you can see in 2.10.0 there is a lot of more going on. My example uses a rather simple List container component und all the list item components are memoized. In a more complex case or if inexperienced users don't memoize, the issue will certainly be more pronounced.


> Yes, there is no bug, state is change only for scroll event, or in dynamic mode when size of item is different from cached one. It was changed here cf19d1f

I still can't imagine why it would be desired behavior to trigger a render of the `useVirtual()` for every _pixel_ the user scrolls (which seems to be the case in v2.10.0). Instead it should only trigger a rerender if the user scrolls for enough for the actual list items to change. E.g. For example if the list items are of 30px height, the list component should only rerender if the user scrolls for around 30px, because only then virtualized list items get added/removed.

**Comment by piecyk** [comment]
@karex problem in your example is that, you are attaching measureRef on row, and on cell, https://codesandbox.io/s/depth-exceeded-demo-forked-f90er It works in older versions as there was another bug that, we only updated visible range on scroll.

> I still can't imagine why it would be desired behavior to trigger a render of the useVirtual() hook for every pixel the user scrolls (which seems to be the case in v2.10.0).

@bernhardc mostly because it's simplifies stuff, but yeah, as user of the lib you should not care about it. 

Thanks for this, will look into reverting from re-rendering on scroll 👍

**Comment by bernhardc** [comment]
@piecyk Great, and thank you for working on this library!

**Comment by karex** [comment]
Yeah, @piecyk , the measureRef was included twice in error indeed. But this is not the cause of the error, your sandbox breaks too.

**Comment by tannerlinsley** [comment]
We've recently reverted the 2.10 breaking change on master and pushed a new patch release. That doesn't technically fix this perf regression, but it makes it within reach. @piecyk we should probably roll back the pixel-based rerendering on 2.x and figure out a better perf strategy with the other breaking changes in the `next` branch.

**Comment by nyanyani** [comment]
Is there any chance to make `scrollOffsetFn: Function(event: Event, prevOffset: number) => number`, and calculate offset value inside useState callback in v2.x? I think it's might be a workaround like #242.
```js
// Just add one parameter to pass previous offset value to `scrollOffsetFn`
const onScroll = event => {
  setScrollOffset(prevOffset => {
    const offset = scrollOffsetFnRef.current ? scrollOffsetFnRef.current(event, prevOffset) : element[scrollKey]

    return offset
  })
}
```
vs
https://github.com/TanStack/react-virtual/blob/081de4745267cf3709d5dc0dd915730427841cd8/src/index.js#L124-L130

**Comment by tannerlinsley** [comment]
This seems to be alleviated somewhat in v3 beta. If it's encountered in the new beta, I'd like a new issue to be opened with a new codesandbox repro. Thanks!

**Comment by osdiab** [comment]
I haven't been able to make a repro trigger this in a sandbox, but with the v3 beta i am getting a maximum update exceeded error every time I render our components (unless I remove `measureElement` from each items' `ref`s), and with v2.10.4 it generally seems fine but i'm experiencing the same max update exceeded error in certain pages on our app. happy to give you access to our code if you want to try reproing it on our app.
