### ISSUE TITLE
Scroll Snap does not work

### ISSUE THREAD

**Issue by casprwang** [TanStack/virtual#478]
### Describe the bug

Scroll snap css does not work on virtual list.

the behavior is well documented here:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Basic_concepts

https://user-images.githubusercontent.com/19645990/213615557-3cbab1fd-8337-4741-9319-2b1e2732af8d.mov

### Your minimal, reproducible example

https://codesandbox.io/s/modest-shape-sk0nce?file=/src/main.tsx

### Steps to reproduce

scroll on the first virtual list

### Expected behavior

it should scroll smoothly and snap at each rows

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/19645990/213615589-c2c92ae6-986f-4680-adf8-bb9b1906dd39.mov

### Platform

macos, chrome

### tanstack-virtual version

beta.39

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by dcastil** [comment]
I have the same issue in `3.0.0-beta.54`.

Looks like this was an issue before already: https://github.com/TanStack/virtual/issues/267

**Comment by tokenosopher** [comment]
Any news on this one?

**Comment by dcastil** [comment]
In the meantime I figured out that this is a limitation of the browser and not related to the library.

When you add or remove scroll snap elements during scrolling, Chrome glitches like in the video above. The only workaround that worked for me was to render the scroll snap elements statically "on top" of the virtualized elements so that they don't change during scrolling.

**Comment by tannerlinsley** [comment]
To help triage a lot of outdated issues, we're closing this due to its age. If this issue is still relevant, please tag @ tannerlinsley in a new comment confirming the case.

**Comment by kieranm** [comment]
@tannerlinsley I'm not sure if this is possible or not but I do think it warrants further investigation to see if we can come up with a solution that works. It would be really useful to get scroll-snap working. Thanks!

**Comment by mrlubos** [comment]
Hey @tannerlinsley, this appears to be still relevant as of `3.0.0-beta.68`

**Comment by kieranm** [comment]
I have looked into this extensively, and due to browser limitations, the only way to get this working is to overlay extra divs on top of the usual divs with the snap points in place. These snap points can only be updated when the user is not scrolling.

Given that this is a headless library, I don't think there's any way to add support for it.

**Comment by mrlubos** [comment]
That makes total sense @kieranm, thanks for the update!

**Comment by RicoMentz** [comment]
@tannerlinsley This issue is definitely still relevant, just ran into the same problem on a really important project, thanks.

**Comment by intergalacticspacehighway** [comment]
@kieranm thank for the update. Can you share some example with css scroll snap working, will be really helpful! 😄

**Comment by Azarattum** [comment]
Has anyone found a workaround? I have a virtual list (not the TanStack one, my vanilla implementation) that has elements with `scroll-snap-type: x` (which is completely unrelated to scrolling of the list itself since it scrolls in the `y` axis). When I try to use `scrollIntoView` in Chrome it stops when a new DOM element with snap is created.
