### ISSUE TITLE
Tag appropriate version as the latest

### ISSUE THREAD

**Issue by dn-l** [TanStack/virtual#507]
### Describe the bug

Current latest version is [3.0.0-alpha.1](https://www.npmjs.com/package/@tanstack/virtual-core/v/3.0.0-alpha.1) which causes a downgrade when I use `pnpm up --latest`.

<img width="764" alt="Screenshot 2023-02-14 at 23 30 16" src="https://user-images.githubusercontent.com/7160998/218767627-d5ee7ad2-9615-4df3-b564-9ef4808b063b.png">

### Your minimal, reproducible example

I doubt it's needed

### Steps to reproduce

`pnpm up --latest`

### Expected behavior

Installs [3.0.0-beta.48](https://www.npmjs.com/package/@tanstack/virtual-core/v/3.0.0-beta.48)

### How often does this bug happen?

Every time

### Platform

macOS

### tanstack-virtual version

^3.0.0-beta.41

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by ablakey** [comment]
Came here to raise this. 

The documentation on the website does not match the API (eg. "useVirtual" vs. "useVirtualized"  "size" vs. "count". So I wanted to see what version to use.  It's kind of weird that I get an "alpha" version but "beta" versions are seen as less-appropriate to be treated as the latest stable.

P.S. thanks for making and maintaining this software. The choice to make it a function rather than component is delightful.

**Comment by dn-l** [comment]
No longer relevant to me - using [virtuoso](https://github.com/petyosi/react-virtuoso) instead.

**Comment by glecetre** [comment]
Hello, I think this can be reopened because it's still the case and the save behaviour happens. Beta 9 is marked as latest and following betas are "pre-release". I have doubts whether it's on purpose or not, and whether I should use beta 9 or the latest beta.
