### ISSUE TITLE
Container automatically scrolls to top, when using dynamic sized items based on web-components

### ISSUE THREAD

**Issue by veithlukas** [TanStack/virtual#525]
### Describe the bug

We encounter strange scrolling behaviour when using tanstack-virtual with dynamically sized virtual elements like `Card` from @ui5-webcomponents-react.
I adapted the dynamic example from the official example sandbox 

Container 1: 
If you scroll down the first container to the bottom and then scroll-up, the container scrolls automatically to the top. 

Container 2: 
I added a plain JSX <span> element to the virtual-element container. -> Now scrolling and virtualization works as expected. I have no clue why this is happening.

I would appreciate some guidance if there is bug in my Card Component or this is a bug in tanstack-virtual. 

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/prod-dawn-xpotyh?file=%2Fsrc%2Fmain.tsx&selection=%5B%7B%22endColumn%22%3A35%2C%22endLineNumber%22%3A67%2C%22startColumn%22%3A35%2C%22startLineNumber%22%3A67%7D%5D

### Steps to reproduce

Scroll down the container till bottom and then scroll up. 

### Expected behavior

Container should scroll up normally when reaching the bottom of the container. 

### How often does this bug happen?

Every time

### Platform

- macOS Chrome 110

### tanstack-virtual version

v3.0.0 beta 52

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@veithlukas looks like it's because in time of rendering when item mount, size of is 0, then resize observer callback is triggered with real size. There is special logic when we read sizes for items before scroll offset to adjust the scroll position main to compensate the difference between estimated size and real size.

We can disbale the scroll adjustments in scrollToFn, but the real question whey initial `size is 0`?

https://codesandbox.io/p/sandbox/magical-ishizaka-hgdbsq
